/// Flutter icons MainIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MainIcons
///      fonts:
///       - asset: fonts/MainIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MainIcons {
  MainIcons._();

  static const _kFontFam = 'MainIcons';
  static const String _kFontPkg = null;

  static const IconData cow_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_icon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_icon =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_icon =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_icon =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_list_icon =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
