name: agriterra
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # AutoRoute is a declarative routing solution, where everything needed for navigation is automatically generated for you.
  auto_route: ^0.6.9

  # Functional Programming in Dart, Option, Either, State, Tuple, Free, Lens and other tools for programming in a functional style.
  dartz: ^0.9.2

  # A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
  dio: ^3.0.10

  # An abstract class that helps to implement equality without needing to explicitly override == and hashCode.
  equatable: ^1.2.5

  # A flexible widget for user notification. Customize your text, button, duration, animations and much more. For Android devs, it is made to replace Snackbars and Toasts.
  flushbar: ^1.10.4

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern.
  flutter_bloc: ^6.1.1

  # Annotations for the freezed code-generator.
  freezed_annotation: ^0.12.0

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in the App
  get_it: ^5.0.3

  # Injectable is a convenient code generator for get_it
  injectable: ^1.0.5

  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^1.6.24

  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^0.5.12+4

  # A package that provides an easy way to add skeleton text loading animation in Flutter project.
  skeleton_text: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # AutoRoute is a declartive routing solution, where everything needed for navigation is automatically generated for you.
  auto_route_generator: ^0.6.10

  # A build system for Dart code generation and modular compilation.
  build_runner:

  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^0.12.6

  # Injectable is a convenient code generator for get_it.
  injectable_generator: ^1.0.6

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/menu_icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: MainIcons
      fonts:
        - asset: fonts/MainIcons.ttf

